# Learnt from https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/travis_cpp_tutorial.pdf

language: cpp
compiler:
  - gcc
  - clang
dist: trusty

# Adding environment variables
env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
addons:
  apt:
    packages:
      - clang-3.8
    sources: *sources

# C++14
before_install:
  - sudo add-apt repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++ -6 90
  - sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 90
  - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 90
  - sudo apt-get install -y libc++-dev libc++abi-dev
 
script:
  - qmake
  - make
  - ./travis-qmake-gcc-clang-cpp14
