# Learnt from https://github.com/richelbilderbeek/travis_cpp_tutorial/blob/master/travis_cpp_tutorial.pdf

language: cpp
compiler:
  - gcc
  - clang
dist: trusty

# C++14
before_install:
  - sudo add-apt repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++ -6 90
 
script:
  - qmake
  - make
  - ./travis-qmake-gcc-clang-cpp14
